version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-stretch
    working_directory: /go/src/github.com/ParticleDecay/namecheck
    environment:
      GO111MODULE: "on"
    steps:
      - checkout

      - run: go mod tidy
      - run: go test -v ./...
