version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11beta3-stretch
    working_directory: /go/src/github.com/ParticleDecay/namecheck
    steps:
      - checkout

      - run: dep ensure -v
      - run: go test -v ./...