version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11beta3-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: dep ensure
      - run: go test -v ./...